
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox5;
	
	private global::Gtk.Image imagePicture;
	
	private global::Gtk.Label labelName;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		global::Stetic.BinContainer.Attach (this);
		this.Name = "MainWindow";
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.imagePicture = new global::Gtk.Image ();
		this.imagePicture.Name = "imagePicture";
		this.vbox5.Add (this.imagePicture);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.imagePicture]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.labelName = new global::Gtk.Label ();
		this.labelName.Name = "labelName";
		this.labelName.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.labelName.UseUnderline = true;
		this.labelName.Wrap = true;
		this.vbox5.Add (this.labelName);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.labelName]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.vbox5);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Hide ();
	}
}
